### ISSUE TITLE
Cannot find module 'browserWindow'

### ISSUE THREAD

**Issue by tuxbox** [develephant/ngElectron#8]
Hi,

when I import the ng-electron.js in the index.html I receive the following error:

`Uncaught Error: Cannot find module 'browserWindow'
Error: Cannot find module 'browserWindow'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at EventEmitter.<anonymous> (/Users/iulius/Code/podplayer/electron-app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:235:70)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/Users/iulius/Code/podplayer/electron-app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)`

Any ideas how to fix that? Maybe it's just the readme that needs some more clarification :-)

**Comment by eddiriarte** [comment]
module name should be 'browser-window'...
I have errors with some other modules: 'nativeImage' -> 'native-image', 'menuItem' -> 'menu-item', 'childProcess' -> 'child_process', etc.... i forked the project and fixed them, its working for me now: https://github.com/eddiriarte/ngElectron and created a pull-request now.
